// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: add_new_message.sql

package models

import (
	"context"
)

const addNewMessage = `-- name: AddNewMessage :one
INSERT INTO "messages"(id, user_id, content, image_url, file_url)
VALUES($1, $2, $3, $4, $5)
RETURNING id, user_id, content, image_url, file_url, deleted, created_at, updated_at
`

type AddNewMessageParams struct {
	ID       string
	UserID   string
	Content  string
	ImageUrl string
	FileUrl  string
}

func (q *Queries) AddNewMessage(ctx context.Context, arg AddNewMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, addNewMessage,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.ImageUrl,
		arg.FileUrl,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ImageUrl,
		&i.FileUrl,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
