// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: add_new_message.sql

package models

import (
	"context"
)

const addNewMessage = `-- name: AddNewMessage :exec
INSERT INTO "messages"(id, user_id, content, image_url)
VALUES($1, $2, $3, $4)
`

type AddNewMessageParams struct {
	ID       string
	UserID   string
	Content  string
	ImageUrl string
}

func (q *Queries) AddNewMessage(ctx context.Context, arg AddNewMessageParams) error {
	_, err := q.db.Exec(ctx, addNewMessage,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.ImageUrl,
	)
	return err
}
