// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_unique_code_request.sql

package models

import (
	"context"
)

const deleteUniqueCodeRequest = `-- name: DeleteUniqueCodeRequest :exec
DELETE FROM "verification_codes"
WHERE email = $1
`

func (q *Queries) DeleteUniqueCodeRequest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUniqueCodeRequest, email)
	return err
}
