// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_user_oauth_account.sql

package models

import (
	"context"
)

const findUserOauthAccount = `-- name: FindUserOauthAccount :one
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at
FROM "oauth_account"
WHERE user_id = $1
`

func (q *Queries) FindUserOauthAccount(ctx context.Context, userID string) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, findUserOauthAccount, userID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
