// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generate_unique_code.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const generateUniqueCode = `-- name: GenerateUniqueCode :one
INSERT INTO "verification_codes"(id, email, code, expires_at)
VALUES($1, $2, $3, $4)
RETURNING id, code, email, expires_at, created_at, updated_at
`

type GenerateUniqueCodeParams struct {
	ID        string
	Email     string
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GenerateUniqueCode(ctx context.Context, arg GenerateUniqueCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, generateUniqueCode,
		arg.ID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
