// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        string
	UserID    string
	Content   string
	ImageUrl  string
	FileUrl   string
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type OauthAccount struct {
	ID             string
	UserID         string
	Provider       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   pgtype.Text
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID            string
	Email         string
	Username      string
	EmailVerified bool
	Avatar        pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type VerificationCode struct {
	ID        string
	Code      string
	Email     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
