name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Debug - Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
          pwd
          whoami
          ls -la ~/projects/go-community
          cd ~/projects/go-community
          git remote -v
          git status

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
          echo "Pulling changes from GitHub."
          cd ~/projects/go-community
          git fetch origin main
          git reset --hard origin/main

          echo "Building and starting Docker container in server directory."
          cd ~/projects/go-community/server
          docker compose down
          docker compose up --build -d

          echo "Building the Nuxt app and starting pm2 in app directory."
          cd ~/projects/go-community/app

          # Install global dependencies if needed
          command -v pnpm &> /dev/null || npm install -g pnpm
          command -v pm2 &> /dev/null || npm install -g pm2
            
          # Install dependencies
          echo "Installing dependencies..."
          pnpm install
          
          # Lint and build
          echo "Running lint and build..."
          pnpm run lint:fix
          pnpm run build
          
          # Restart application
          # pm2 restart ecosystem.config.cjs || pm2 start ecosystem.config.cjs
          
          echo "Deployment completed successfully!"
